name: Release Build

on:
#  push:
#    branches:
#      - main
#  pull_request:
  workflow_dispatch:


jobs:
  sign_apk:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
 
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
 
    - name: Decode keystore
      env:
        KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
      run: echo $KEYSTORE_BASE64 | base64 --decode > my-release-key.keystore
 
    - name: Build and sign APK
      run: |
          chmod +x gradlew
          ./gradlew assemblerelease -Pandroid.injected.signing.store.file=my-release-key.keystore -Pandroid.injected.signing.store.password=${{ secrets.KEYSTORE_PASSWORD }} -Pandroid.injected.signing.key.alias=my-alias-name -Pandroid.injected.signing.key.password=${{ secrets.KEYSTORE_KEY_PASSWORD }}
